:- ensure_loaded(knowledge_base)
:- ensure_loaded(horn_clause)

% Queries

% ?- query2([italy], [REGION], [GRAPE], FRUITY, BOLD, SAVORY, DRY, TANNIN, [DISH], [NOTCOUNTRY], [NOTREGION], [NOTGRAPE], [NOTDISH], STRONG_WINE, WEAK_WINE).

% ?- {STRONG_WINE, WEAK_WINE}/(query2([italy], [REGION], [GRAPE], FRUITY, BOLD, SAVORY, DRY, TANNIN, [DISH], [NOTCOUNTRY], [NOTREGION], [NOTGRAPE], [NOTDISH], STRONG_WINE, WEAK_WINE)).

% ?- distinct({STRONG_WINE, WEAK_WINE}/(query2([italy], [REGION], [GRAPE], FRUITY, BOLD, SAVORY, DRY, TANNIN, [DISH], [NOTCOUNTRY], [NOTREGION], [NOTGRAPE], [NOTDISH], STRONG_WINE, WEAK_WINE))).
?- distinct(query2([italy], [_REGION], [_GRAPE], _FRUITY, _BOLD, _SAVORY, _DRY, _TANNIN, [_DISH], [_NOTCOUNTRY], [_NOTREGION], [_NOTGRAPE], [_NOTDISH], STRONG_WINE, WEAK_WINE)).

% ?- distinct({STRONG_WINE, WEAK_WINE}/(query3([italy], [REGION], [GRAPE], FRUITY, BOLD, SAVORY, DRY, TANNIN, [DISH], [NOTCOUNTRY], [NOTREGION], [NOTGRAPE], [NOTDISH], STRONG_WINE, WEAK_WINE))).
?- distinct(query3([italy], [_REGION], [_GRAPE], _FRUITY, _BOLD, _SAVORY, _DRY, _TANNIN, [_DISH], [_NOTCOUNTRY], [_NOTREGION], [_NOTGRAPE], [_NOTDISH], STRONG_WINE, WEAK_WINE)).
